# Generated by Django 2.2.5 on 2019-09-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=120, null=True)),
                ('corp_de_la_notification', models.CharField(max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
