# Generated by Django 2.2.5 on 2019-09-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note1', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=25, null=True)),
                ('note2', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=25, null=True)),
                ('note3', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=25, null=True)),
                ('note4', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=25, null=True)),
                ('note5', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=25, null=True)),
                ('note6', models.CharField(choices=[('1', '1'), ('2', '2')], max_length=25, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
