# Generated by Django 2.2.5 on 2019-09-12 14:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='paiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paye', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('valid_until', models.DateField(default=datetime.date(2019, 10, 1), verbose_name='valid until')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
