# Generated by Django 2.2.5 on 2019-09-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('Planning', models.ImageField(upload_to='planning/')),
                ('message', models.TextField(default=' ', null=True)),
                ('daily_img', models.ImageField(null=True, upload_to='daily-img/')),
                ('group', models.CharField(choices=[('petit-section', 'Petit-Section'), ('moyenne-section', 'Moyenne-Section'), ('grand-section', 'Grand-Section')], max_length=250)),
                ('Event_title', models.CharField(blank=True, max_length=100)),
                ('Event_description', models.TextField(blank=True, default=' ', null=True)),
                ('Event_date', models.DateField(blank=True, null=True)),
                ('Event_img', models.ImageField(null=True, upload_to='events/')),
            ],
        ),
    ]
